apiVersion: v1
kind: Service
metadata:
  name: config-service
  namespace: {{ .Values.tenantNamespace }}
  labels:
    app: config-service
spec:
  ports:
  - name: grpc-web
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
  - name: http
    port: {{ .Values.service.httpPort }}
    targetPort: {{ .Values.service.httpPort }}     
  selector:
    app: config-service
