    CREATE TABLE IF NOT EXISTS "CONNECTIONS_JSON" (
      "ID" TEXT PRIMARY KEY,
      "DATA" JSONB
    );

    CREATE TABLE IF NOT EXISTS "DEVICES" (
      "DEVICEEUI" TEXT PRIMARY KEY,
      "SERIALNUMBER" INTEGER,
      "MACADDRESS" TEXT,
      "MODELTYPE" INTEGER,
      UNIQUE("SERIALNUMBER")
    );

    CREATE TABLE IF NOT EXISTS "IMAGES" (
      "ID" TEXT PRIMARY KEY,
      "CONNECTIONID" TEXT NOT NULL,
      "DATA" JSONB
    );

    CREATE INDEX IF NOT EXISTS images_connectionid on "IMAGES"("CONNECTIONID");

    CREATE TABLE IF NOT EXISTS "CONFIG" (
      "ID" SERIAL,
      "CONNECTIONID" TEXT NOT NULL,
      "SLOT" INTEGER NOT NULL DEFAULT 0,
      "NAME" TEXT NOT NULL,
      "DESIRED" TEXT,
      "REPORTED" TEXT,
      UNIQUE("CONNECTIONID", "SLOT", "NAME")
    );

    CREATE INDEX IF NOT EXISTS config_connectionid on "CONFIG"("CONNECTIONID");

    CREATE TABLE IF NOT EXISTS "CONFIG_SCHEMA" (
      "ID" SERIAL,
      "PPDEV" TEXT NOT NULL,
      "PPVER" TEXT NOT NULL,
      "PPORDER" INTEGER NOT NULL,
      "NAME" TEXT NOT NULL,
      "INDEX" INTEGER NOT NULL,
      "DESCRIPTION" TEXT NOT NULL DEFAULT '',
      "DEFAULT" TEXT NOT NULL DEFAULT '',
      "MIN" TEXT NOT NULL DEFAULT '',
      "MAX" TEXT NOT NULL DEFAULT '',
      "TYPE" TEXT NOT NULL,
      UNIQUE("PPDEV", "PPVER", "NAME")
    );

    CREATE INDEX IF NOT EXISTS config_schema_name on "CONFIG_SCHEMA"("NAME");